name: Self-Hosted Runner Example

on:
  push:
    branches:
      - main

jobs:
  print-current-directory:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Current Directory
        run: pwd
