name: Update DNS Configuration

on:
  push:
    branches:
      - main

jobs:
  update-dns:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Replace DNS Zone File on Server
        run: |
          echo "Uploading new DNS zone file to server..."
          scp ./db.tt.miaj.tech srvadmin@10.225.150.11:/tmp/db.tt.miaj.tech
          
          echo "Replacing old file with the new one..."
          ssh srvadmin@10.225.150.11 << 'EOF'
            sudo mv /tmp/db.tt.miaj.tech /var/cache/bind/zones/db.tt.miaj.tech
            sudo systemctl reload bind9
          EOF
